---
# github.com/AlDanial/cloc
header :
  cloc_url           : github.com/AlDanial/cloc
  cloc_version       : 1.67
  elapsed_seconds    : 0.0172619819641113
  n_files            : 1
  n_lines            : 59
  files_per_second   : 173.792326178835
  lines_per_second   : 53817.6903400459
  report_file        : Dockerfile.yaml
Dockerfile :
  nFiles: 1
  blank: 5
  comment: 1
  code: 53
SUM:
  blank: 5
  comment: 1
  code: 53
  nFiles: 1
