---
# github.com/AlDanial/cloc
header : 
  cloc_url           : github.com/AlDanial/cloc
  cloc_version       : 1.71
  elapsed_seconds    : 0.00575685501098633
  n_files            : 1
  n_lines            : 58
  files_per_second   : 173.705955437754
  lines_per_second   : 10074.9454153897
  report_file        : ../outputs/Dockerfile.yaml
Dockerfile :
  nFiles: 1
  blank: 4
  comment: 1
  code: 53
SUM: 
  blank: 4
  comment: 1
  code: 53
  nFiles: 1
