---
# github.com/AlDanial/cloc
header : 
  cloc_url           : github.com/AlDanial/cloc
  cloc_version       : 1.67
  elapsed_seconds    : 0.00490713119506836
  n_files            : 1
  n_lines            : 133
  files_per_second   : 203.785054902342
  lines_per_second   : 27103.4123020115
  report_file        : Makefile.yaml
make :
  nFiles: 1
  blank: 22
  comment: 49
  code: 62
SUM: 
  blank: 22
  comment: 49
  code: 62
  nFiles: 1
