# This workflow will build a container image,
# to run all tests (syntax checking + integration tests) on each PR and git push.

on: [push, pull_request]

name: Run all tests

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run tests
      id: run-tests
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container to run tests
        docker build . --target test
