name: Build Windows executable

on:
  push:
    branches :
      - master

jobs:
  win_exe :
  runs-on : windows-latest
  steps :
    - name : Pull latest cloc source code
      uses: actions/checkout@v4
    - run: git checkout HEAD^
    - name : Install Strawberry Perl
      run: |
        choco install strawberryperl
        echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" >> $GITHUB_PATH
    - name: Show Perl installation details
      run: perl -V

# incomplete
# https://stackoverflow.com/questions/72367353/testing-perl-on-windows-with-github-actions
